### ISSUE TITLE
how the ShortBuffer transform to wav file?

### ISSUE THREAD

**Issue by Undertone0809** [MDZhB/jt-adpcm#1]
I want to know how to convert  shortBuffer into wav file after  decoding the ADPCM?

**Comment by MDZhB** [comment]
> I want to know how to convert shortBuffer into wav file after decoding the ADPCM?

As things stand, you'd have to generate the wav header yourself and dump the contents of the buffer in the data section. Because I made this port for use with my own custom container, that functionality is presently not available in this library.

There's some half-finished code for this purpose in the tests folder (it reads but doesn't dump WAV files). Since this seems like a common use case, I'll clean it up and make it API sometime this week.

**Comment by MDZhB** [comment]
Just an update: code for wav file I/O is basically done and appears to be working correctly. I need to write some additional tests and add documentation, which I plan to do over the next few days. After that, I'd like to migrate to JUnit 5; with those two things in place, I'll roll out a new release.

**Comment by MDZhB** [comment]
@Undertone0809 Version 1.1.0 is up on maven central: https://repo1.maven.org/maven2/com/github/mdzhb/jt-adpcm/. You can use the `WAVFile` class in the `utils` package to read and write WAV files. I've also added usage examples to the readme.
